---
- name: Update nginx config
  template: src=nginx.conf.j2 dest=/etc/nginx/nginx.conf owner=root group=root mode=0644

- name: Update default site
  template: src=default.j2 dest=/etc/nginx/sites-available/default owner=root group=root mode=0644

- name: Add mime type for log
  sudo: true
  shell: /usr/bin/replace "txt;" "txt log;" -- /etc/nginx/mime.types

- name: Restart nginx service
  sudo: true
  service: name=nginx state=restarted
