---
- name: Install packages
  become: true
  become_user: root
  apt: pkg={{ item }} state=installed update_cache=yes autoremove=yes
  with_items:
    # Basics
    - build-essential
    - zip
    - s3cmd
    - bundler
    - memcached
    - redis-server
    - npm
    - nodejs-legacy
    - python-setuptools
    - python-mysqldb

    # Database
    - mysql-server-5.7

    # Web Dev
    - nginx
    - php-cli
    - php-fpm
    - php-gd
    - php-mcrypt
    - php-imap
    - php-mysql
    - php-curl
    - php-json
    - php-xdebug
    - php-redis
    - php-memcached
    - php-intl
    - php-mbstring
    - php-pear

    # Other tools
    - ruby
    - ruby-dev
    - libsqlite3-dev
    - swaks

- name: Set correct timezone
  copy: src=/usr/share/zoneinfo/{{ timezone }} dest=/etc/localtime owner=root group=root mode=0644

- name: Update timezone
  template: src=timezone.j2 dest=/etc/timezone
  notify: update tzdata

- name: Install railsless deploy
  command: gem install -q --no-verbose --no-ri --no-rdoc railsless-deploy -s http://gemcutter.org

- name: Download composer
  get_url: url=https://getcomposer.org/installer dest=/tmp/composer-installer.php mode=0755

- name: Install composer
  become: true
  become_user: root
  shell: php /tmp/composer-installer.php --install-dir=/usr/local/bin --filename=composer
  args:
    creates: /usr/local/bin/composer
  tags: composer

- name: PHP fpm log permissions
  file: path=/var/log/php7.0-fpm.log state=touch mode=0644

