---
- name: Copy MySQL file to server
  template: src=my.cnf.j2 dest=/home/vagrant/.my.cnf owner=vagrant mode=0600

- name: Start MySQL service
  service: name=mysql state=started

- name: Create sites database
  shell: echo 'CREATE DATABASE IF NOT EXISTS dev' | mysql -u root
